### ISSUE TITLE
Punctuation and spaces incorrectly being parsed

### ISSUE THREAD

**Issue by malonehedges** [HarleyKwyn/squirt-reader-N1-plugin#1]
Extra spaces and misc symbols are being rendered as their HTML codes like `&nsbp;`.

**Comment by kwyn** [comment]
Still figuring out how to deal with this one. Might toy with this before I got to sleep tonight. It's hard to handle while avoiding script injections.

**Comment by kwyn** [comment]
I think [this commit](https://github.com/HarleyKwyn/squirt-reader-N1-plugin/commit/27972dae2d5fc494af1f5f8e2d51a761ca43cfb3) fixes this. Let me know if it misses any edge cases on this but for now going to close this issue.
